# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Volkswagen Nappulat Nurmella 2020
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nappulatnurmella.github.io" # the base hostname & protocol for your site, e.g. http://example.com

sign_up_form: "https://docs.google.com/forms/d/e/1FAIpQLSfK5DmdCgIv5Qjh0Jkz_HR2S7J-ycdZm1HfLYuiam7hMc26Dg/viewform"

main_sponsor_logo: vw.jpg
sponsors_with_logos:
  - - rtv.jpg
  - - autopeltityo-koivumaki.png
  - - liedon-asbestipalvelut.png
  - - autojevi.png
  - - pieni-erikoispuoti.png
    - funsense.png
  - - turun_eines.jpg
    - salonen.png
  - - mplus.png
    - lofbergs.png
  - - maritime-tk.png
    - k-rauta.png
  - - gigantti.jpg
    - moi.png
sponsor_names:
  - Auto-Jevi
  - Autopeltityö Koivumäki
  - FunSense
  - Gigantti
  - K-rauta Kuninkoja
  - Leipomo Salonen
  - Liedon Asbestipalvelut
  - Löfbergs
  - M Plus
  - Maritime TK
  - Moi
  - Pieni Erikoispuoti
  - RTV
  - Turun Eines
  - Volkswagen

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
